### ISSUE TITLE
Projection Expression parsing bug

### ISSUE THREAD

**Issue by darylnwk** [aws/aws-dax-go#1]
Hi, I am using Expression Builder to create the Expression for QueryInput. I noticed that Expression Builder Projection delimits with comma and space, eg. "#1, #2". 

As a result, when there is more than 1 projection, the output is incorrect.

Below is an example of QueryOutput.Items
`[
        {
            " #2": {
                "B": null,
                "BOOL": null,
                "BS": null,
                "L": null,
                "M": null,
                "N": null,
                "NS": null,
                "NULL": null,
                "S": "0f3028a2-ee87-447e-9a7a-ee2d94798934",
                "SS": null
            },
            "ID": {
                "B": null,
                "BOOL": null,
                "BS": null,
                "L": null,
                "M": null,
                "N": null,
                "NS": null,
                "NULL": null,
                "S": "9bbef19476623ca56c17da75fd57734dbf82530686043a6e491c6d71befe8f6e",
                "SS": null
            }
        }
    ]`

The value of expr.Names() is `{
        "#0": "RepoID",
        "#1": "ID",
        "#2": "TokenID"
    }`
The value of expr.Projection() is `#1, #2`

The same Expression Builder works without DAX.

Edit: A workaround I am currently using is to specify ProjectionExpression without using Expression Builder

**Comment by anandsas** [comment]
This will be fixed in the next release
