### ISSUE TITLE
Plans for new point release?

### ISSUE THREAD

**Issue by ryanschneider** [aws/aws-dax-go#10]
Any plans to release a new v1 release w/ https://github.com/aws/aws-dax-go/pull/9?

Currently if we try to use newer versions of the `aws-go-sdk` w/ the dax SDK we get this compilation error:

```
# github.com/INFURA/inf-reverse-proxy/vendor/github.com/aws/aws-dax-go/dax
vendor/github.com/aws/aws-dax-go/dax/service.go:129:5: cannot use (*Dax)(nil) (type *Dax) as type dynamodbiface.DynamoDBAPI in assignment:
	*Dax does not implement dynamodbiface.DynamoDBAPI (missing DescribeEndpoints method)
```

Our workaround is either to pin to an old version of `aws-sdk-go` or to use the `aws-dax-sdk` version from master, but would prefer to use recent official releases for both packages.

**Comment by lyaoxion** [comment]
Thanks for reaching out. 

We just released a new version v1.0.2 with #9.
