### ISSUE TITLE
Compatiblity with 1.16 SDK releases?

### ISSUE THREAD

**Issue by ryanschneider** [aws/aws-dax-go#11]
Now that #10 is closed and 1.0.2 is released, I tried upgrading both our our dependencies to the latest versions:

aws-dax-go: 1.0.2
aws-sdk-go: 1.16.6

However, when I do so dax fails to compile:

```
vendor/github.com/aws/aws-dax-go/dax/service.go:129:5: cannot use (*Dax)(nil) (type *Dax) as type dynamodbiface.DynamoDBAPI in assignment:
	*Dax does not implement dynamodbiface.DynamoDBAPI (missing TransactGetItems method)
```

Which version(s) of the aws-sdk-go is 1.0.2 compatible with?

**Comment by jdhardy** [comment]
aws-dax-go v1.0.2 should be compatible with aws-sdk-go up to and including v1.15.84; the transactions APIs were introduced in v1.15.85, which is what breaks compilation.

A version of aws-dax-go that supports transactions will be released shortly.
