### ISSUE TITLE
How to attach routes to the Dax Cluster

### ISSUE THREAD

**Issue by Arnaldo-Manjate** [aws/aws-dax-go#24]
Hi there 

I need assistance making a query to a DynamoDB table through the Dax .After reading through the Code i see that the only way to get the Error "Service Unavailable : no routes found" is the endpoint or the port are not found in the confuguration 

please correct me on how i can attach me endpoint 
![client](https://user-images.githubusercontent.com/52455180/80098940-fd8c9600-856d-11ea-8ed2-d000d68f884c.png)

Error :
![2](https://user-images.githubusercontent.com/52455180/80099215-67a53b00-856e-11ea-9b61-1f37a87921c1.png)

This is where the error is occurring : 
![AwsErr](https://user-images.githubusercontent.com/52455180/80099805-5c064400-856f-11ea-9b36-db4fab1c8f9c.png)

I am currently getting this error when testing code that I implemented to test queries through the Dax Cluster

**Comment by jiaqihu-A** [comment]
> Hi there
> 
> I need assistance making a query to a DynamoDB table through the Dax .After reading through the Code i see that the only way to get the Error "Service Unavailable : no routes found" is the endpoint or the port are not found in the confuguration
> 
> please correct me on how i can attach me endpoint
> ![client](https://user-images.githubusercontent.com/52455180/80098940-fd8c9600-856d-11ea-8ed2-d000d68f884c.png)
> 
> Error :
> ![2](https://user-images.githubusercontent.com/52455180/80099215-67a53b00-856e-11ea-9b61-1f37a87921c1.png)
> 
> This is where the error is occurring :
> ![AwsErr](https://user-images.githubusercontent.com/52455180/80099805-5c064400-856f-11ea-9b36-db4fab1c8f9c.png)
> 
> I am currently getting this error when testing code that I implemented to test queries through the Dax Cluster

Hello, 

we have sample code here to demonstrate how to use DAX Go client. https://github.com/aws-samples/aws-dax-go-sample/blob/master/try_dax.go#L213

The error you attached can also indicate a network problem. We recommend you to check your network security group setting to ensure the host you run the client can connect to DAX node.

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.create-cluster.cli.configure-inbound-rules.html

**Comment by Arnaldo-Manjate** [comment]
Thank you it was indeed a security group issue , It has been resolved thanks


*Arnaldo Manjate*
Developer

| T  011 680 0540
| E arnaldo@rapidtrade.com <shaun@rapidtrade.com>
| www.rapidtrade.com

**Comment by web3coach** [comment]
Ah the hours I wasted on this. My problem was not running my program from within the AWS VPC. I thought it's a security group issue as well. Then I scp my program binary to EC2, run it, and voila... I queried an Item from my DAX.

DAX is only accessible from AWS VPC!
