### ISSUE TITLE
ScanPage/QueryPage support

### ISSUE THREAD

**Issue by zabawaba99** [aws/aws-dax-go#3]
Are there any plans to support ScanPage/QueryPage or any particular reason that they are not implemented? I'm interested in implementing them but wanted to touch base before opening up a PR.

**Comment by jdhardy** [comment]
There was no particular reason they were left out, so a PR would be very much appreciated.

**Comment by ktseytlin** [comment]
Thank you @zabawaba99 for your request! Support has been added for v1.1.6. :)
