### ISSUE TITLE
Update transaction limit to 100

### ISSUE THREAD

**Issue by miparnisari** [aws/aws-dax-go#40]
https://github.com/aws/aws-dax-go/blob/8524b5d9a6599f1f44ecf30cc52dac8324f54c6a/dax/internal/client/request.go#L431

But Dynamo updated their transaction limit to 100: https://aws.amazon.com/about-aws/whats-new/2022/09/amazon-dynamodb-supports-100-actions-per-transaction/

**Comment by sumitsa-amazon** [comment]
Closing this issue as the underlying PR is closed.
