### ISSUE TITLE
DescribeEndpoints

### ISSUE THREAD

**Issue by ezuhl** [aws/aws-dax-go#7]
Hi I am getting an issue where Dax does not implement dynamodbiface.DynamoDBAPI
ie.

vendor/github.com/aws/aws-dax-go/dax/service.go:129:5: cannot use (*Dax)(nil) (type *Dax) as type dynamodbiface.DynamoDBAPI in assignment:
        *Dax does not implement dynamodbiface.DynamoDBAPI (missing DescribeEndpoints method)

**Comment by ezuhl** [comment]
Im guessing this is because of the aws-sdk update.

**Comment by sjbodzo** [comment]
It would appear this is the exact issue: [https://github.com/aws/aws-sdk-go/commit/80ad2657c5ff975b642b1febb11c3fcfd747c057#diff-860e6a2161ab14dca3a32e5689cd69ad](url)

**Comment by ezuhl** [comment]
closing
